### PR TITLE
More links to talk recordings

### PR DESCRIPTION
**Pull request by th0n0s**

### CODE REVIEW

**Review by swvanbuuren — CHANGES_REQUESTED** [review]
Why are you creating a new page wit recordings?
Why not add the recordings links to each individual keynote/talks page?
The recordings page is also not listed in the menu.

My advice is: 
Change the presentation macro (https://github.com/boschglobal/embedded-linux/blob/master/include/presentation.md?plain=1): 
- Duplicate the slides part. Rename the section to Recording, keyword to `recording`and make other appropriate changes.
- Then you can add a link to `keynotes.yaml` or `talks.yaml` to display a link on each individual keynote or talk page.

**Comment by th0n0s** [comment]
Thanks for your advice. We discussed what would be the easiest way to provide the links. Because we are not very familar with your macro structure, we decided to add a new recording page and add a link on top of the "speaker" page. Initially I wanted to add a new menue item, but  wasn't sure and didn't want to destroy something.
Because there were many requests we published the page with keynote recordings yesterday and shared it with the LF EU. So if you don't mind I'd  like to proceed with the new recording page as a interim solution and once you are back you could do it in the right way

**Comment by th0n0s** [comment]
Also, Philipp and I are on vacation next week. I don't know whether Dirk/Fofi can implement what you requested

**Comment by th0n0s** [comment]
let me give it a trial this aftenoon. Problem is that I can't verify if my changes work.

**Review by swvanbuuren — APPROVED** [review]

**Comment by swvanbuuren** [comment]
@th0n0s ok, you can merge if you'd like.

Fwiw, you could ask someone from the MVP team to make the changes I am suggesting.

**Pull request merged**
